services:
  postgres:
    image: postgres:16-alpine
    container_name: payder-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: payder
      POSTGRES_PASSWORD: payder
      POSTGRES_DB: payder
    ports:
      - "5432:5432"
    volumes:
      - payder_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payder -d payder"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: payder-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: payder-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@payder.local
      PGADMIN_DEFAULT_PASSWORD: payder
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  payder_postgres_data:
